// <auto-generated />
using System;
using EcoX9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcoX9.Migrations
{
    [DbContext(typeof(EcoX9Context))]
    [Migration("20210719193821_tipos")]
    partial class tipos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EcoX9.Models.Ocorrencias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BAIRRO");

                    b.Property<string>("COD_OCO");

                    b.Property<string>("DESC_INFRA");

                    b.Property<string>("DESC_OCO");

                    b.Property<DateTime>("DT_OCO");

                    b.Property<string>("ENDERECO");

                    b.Property<string>("FLAG");

                    b.Property<string>("FLAG_SIT");

                    b.Property<string>("FOTO");

                    b.Property<string>("PONTO_REF");

                    b.Property<long?>("Tipo_OcorrenciaID");

                    b.Property<long>("TiposId");

                    b.Property<long>("UsuariosId");

                    b.HasKey("Id");

                    b.HasIndex("Tipo_OcorrenciaID");

                    b.HasIndex("UsuariosId");

                    b.ToTable("tb_ocorrencias");
                });

            modelBuilder.Entity("EcoX9.Models.Tipo_Ocorrencia", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DESC_TIPO");

                    b.Property<string>("NOME_TIPO");

                    b.HasKey("ID");

                    b.ToTable("Tipo_Ocorrencia");
                });

            modelBuilder.Entity("EcoX9.Models.Usuarios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CHAPA");

                    b.Property<string>("CPF");

                    b.Property<string>("EMAIL");

                    b.Property<string>("FLAG");

                    b.Property<string>("FLAG_SIT");

                    b.Property<string>("NOME");

                    b.Property<string>("SENHA");

                    b.Property<string>("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("tb_usuarios");
                });

            modelBuilder.Entity("EcoX9.Models.Ocorrencias", b =>
                {
                    b.HasOne("EcoX9.Models.Tipo_Ocorrencia", "Tipo_Ocorrencia")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("Tipo_OcorrenciaID");

                    b.HasOne("EcoX9.Models.Usuarios", "Usuarios")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
