// <auto-generated />
using System;
using EcoX9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EcoX9.Migrations
{
    [DbContext(typeof(EcoX9Context))]
    [Migration("20210718194151_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EcoX9.Models.Ocorrencias", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COD_OCO");

                    b.Property<string>("DESC_OCO");

                    b.Property<DateTime>("DT_OCO");

                    b.Property<string>("FLAG");

                    b.Property<string>("FLAG_SIT");

                    b.Property<string>("FOTO");

                    b.Property<long>("UsuariosId");

                    b.HasKey("Id");

                    b.HasIndex("UsuariosId");

                    b.ToTable("tb_ocorrencias");
                });

            modelBuilder.Entity("EcoX9.Models.Usuarios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EMAIL");

                    b.Property<string>("FLAG");

                    b.Property<string>("FLAG_SIT");

                    b.Property<string>("NOME");

                    b.Property<string>("SENHA");

                    b.Property<string>("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("tb_usuarios");
                });

            modelBuilder.Entity("EcoX9.Models.Ocorrencias", b =>
                {
                    b.HasOne("EcoX9.Models.Usuarios", "Usuarios")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
